### PR TITLE
Added example for sub-flow mocking in java

### PR DESCRIPTION
**Pull request by manikmagar**
Updated document to show how to mock a sub-flow in java test case.

### CODE REVIEW

**Comment by nearnshaw** [comment]
Hi Manik, as this contribution you're making is more significant, I'm afraid we're required to ask you to please take a moment to sign our contributor's agreement as described at https://github.com/mulesoft/mulesoft-docs/blob/master/README.adoc . That way, you'll be registered as a contributor and we can freely accept more of your pull requests in the future.

**Comment by manikmagar** [comment]
I have already accepted that agreement, should I do it again?

**Comment by manikmagar** [comment]
Anyways, accepted it again. Thanks.

- Manik

**Comment by fermujica** [comment]
Thanks Manik. I accepted your PR and I´m adding it below the Java example in our docs. 
It was our bad earlier, there was no need for you to accept the agreement again, but thanks for double checking. 
We appreciate your contribution.

**Comment by manikmagar** [comment]
Thanks for merging it, it was hard to figure out that so I thought of adding in docs to help others. I think you separated the java code from related description of `Matchers.contains`. In that case, it may be a good idea to at least add a reference of bottom java code to the NOTE section that I modified.

**Pull request merged**
