### PR TITLE
clarify what DataWeave actually is

### PR DESCRIPTION
**Pull request by zdenekca**
This is my novice understanding of DataWeave. We should have some basic description of what DataWeave is.

### CODE REVIEW

**Comment by krishahn** [comment]
sgtm, ditch the "simple, powerful ..." marketing lingo

**Comment by zdenekca** [comment]
Hi there,

The updated documentation on DataWeave looks really good. Thanks for making the changes.

I am using MuleSoft product for our first major CloudHub application. This year I will be building many more apps so I should gain a great deal more experience.

Cheers,
Zdenek

**Comment by zdenekca** [comment]
I have more suggestions on how to improve Mule documentation if anyone is interested. I just need contact info to send my ideas and practical examples that I think are missing from the documentation.

**Comment by dukesphere** [comment]
Hi Zdenek,

You can send suggestions directly to me if you like: stacey.duke@mulesoft.com. Thanks for your feedback!

**Pull request closed without merging**
