### PR TITLE
Release Notes, walkthrough updates for RC

### PR DESCRIPTION
**Pull request by IanWhyte**

### CODE REVIEW

**Comment by claudemamo** [comment]
Updated B2B docs according to latest releases; resolved conflicts

**Comment by george-hoffer** [comment]
Ian - Thanks for this. Please watch out for spurious characters - ftps-and-edi-x12-purchase-order-walkthrough.adoc has quite a few - check at the end of line 112 and more thereafter.

Also, DataMapper has been replaced by DataWeave aka Transform Mapping in Studio. Please configure your examples to use DataWeave from now on. We're starting to remove DataMapper references from the docs.

George

**Comment by george-hoffer** [comment]
Please also spell check your content. An example "the FTPS connector assigsn a name for it" + please add a period at the end of sentences. 

Thank you.

**Comment by george-hoffer** [comment]
Please don't use private docs in your files, for example, this Gdoc is private: https://docs.google.com/document/d/1R6H0-pKoO7n5swWerkpKXfO6liDFG3TNsnBnhqKfbTc/edit#heading=h.afo4sqok4iqk

**Comment by IanWhyte** [comment]
Thanks, George, will do. The fact is I didn't review these docs at all
before including them in the pull request; I'll make sure that doesn't
happen again.

Ian

**Comment by IanWhyte** [comment]
George, can you tell me where you're seeing this, please?

Ian

**Pull request merged**
