### PR TITLE
Update component-authorization-using-spring-security.adoc

### PR DESCRIPTION
**Pull request by tonedef71**
Removed superfluous colons.  For consistency, changed single-quotes to double-quotes for attribute definitions.  Corrected spring properties to be constructor arguments where necessary.

### CODE REVIEW

**Comment by tonedef71** [comment]
Why hasn't this change been merged yet?

**Comment by george-hoffer** [comment]
When we get change requests from outside the company, we need to verify that they are correct. Finding someone who can check Spring is daunting.

**Comment by george-hoffer** [comment]
I'm trying harder to find an approver.

**Comment by tonedef71** [comment]
So you are still trying to locate someone who can review the changes in this pull-request?  That is a shame, because the other fixes (for the punctuation and typographical errors) are unnecessarily being held up as well.

**Comment by george-hoffer** [comment]
If you want to submit another PR for just the punctuation issues, I'll approve those.

**Comment by george-hoffer** [comment]
Finally found the answer. Note: Would help us if you list info to verify your request, especially on more esoteric areas like Spring.

http://docs.spring.io/spring-security/site/migrate/current/3-to-4/html5/migrate-3-to-4-xml.html

4.5.8. ProviderManager
ProviderManager has removed the deprecated default constructor and the corresponding setter methods in favor of using constructor injection. It has also removed the clearExtraInformation property since the AuthenticationException had the extra information property removed.
Old:
<b:bean class="org.springframework.security.authentication.ProviderManager">
    <b:property name="parent" ref="parent"/>
    <b:property name="providers">
        <b:list>
            <b:ref bean="authenticationProvider"/>
        </b:list>
    </b:property>
    <b:property name="clearExtraInformation" value="true"/>
</b:bean>
should be changed to

<b:bean class="org.springframework.security.authentication.ProviderManager">
    <b:constructor-arg>
        <b:list>
            <b:ref bean="authenticationProvider"/>
        </b:list>
    </b:constructor-arg>
    <b:constructor-arg ref="parent"/>
</b:bean>

**Comment by tonedef71** [comment]
Thank you for sharing the link.  I did not know that a Spring migration
guide existed.

**Comment by george-hoffer** [comment]
Here's another suspect - would this also qualify for the use of constructor-arg?

 <spring:bean id="authenticationManager" class="org.springframework.security.authentication.ProviderManager">
      <spring:property name="providers">
          <spring:list>
               <spring:ref bean="daoAuthenticationProvider"/>
          </spring:list>
      </spring:property>
</spring:bean>

Perhaps as: (?)

<spring:bean id="authenticationManager" class="org.springframework.security.authentication.ProviderManager">
  <spring:constructor-arg>
    <spring:list>
      <spring:ref bean="daoAuthenticationProvider"/>
    </spring:list>
  </spring::constructor-arg>
</spring:bean>

This is in https://docs.mulesoft.com//mule-user-guide/v/3.8/upgrading-from-acegi-to-spring-security#using-an-authenticationmanager

Thank you!

**Comment by tonedef71** [comment]
You are correct that constructor-args are required since the
org.springframework.security.authentication.ProviderManager class in Spring
Security 4.x has no public default constructor and it also has no public
setProviders() method.

The following looks correct to me (be sure to avoid those double colons in
the fully-qualified element names):

<spring:bean id="authenticationManager" class="org.springframework.
> security.authentication.ProviderManager">
>   <spring:constructor-arg>
>     <spring:list>
>       <spring:ref bean="daoAuthenticationProvider"/>
>     </spring:list>
>   </spring:constructor-arg>
> </spring:bean>



--Tony

**Pull request merged**
