### PR TITLE
AsciiDoc syntax fixes

### PR DESCRIPTION
**Pull request by mojavelinux**
@sleslie23 please consider these changes do touch some content in the /runtime-manager directory...please merge if ok, otherwise kindly advise.

### CODE REVIEW

**Comment by sleslie23** [comment]
@mojavelinux Sorry for the delay! I was on PTO yesterday.

**Comment by mojavelinux** [comment]
Thanks! This will help move the migration along.

**Comment by sleslie23** [comment]
@mojavelinux No problem! Thanks for cleaning up these embarrassing broken links!

FYI, we are working on a massive reorg of the content in the runtime-manager directory. That should be complete by the end of June or before. We'll give you a heads-up as we go along so you won't get hit with any surprises.

**Comment by mojavelinux** [comment]
Thanks!

**Pull request merged**
