### PR TITLE
Update pgp-encrypter.adoc

### PR DESCRIPTION
**Pull request by rajeshdns**
Added more definition on PGP.

### CODE REVIEW

**Comment by rajeshdns** [comment]
looking for successful merge in the portal.

**Comment by george-hoffer** [comment]
Thank you for your contribution. Please complete the contributor's agreement as described on https://docs.mulesoft.com/#making-a-contribution to register as a contributor so that we can accept your pull request.

**Comment by rajeshdns** [comment]
Done, Please accept the pull request.

Rgds
Rajesh

On Tue, Apr 19, 2016 at 10:17 PM, George Hoffer <notifications@github.com>
wrote:

> Thank you for your contribution. Please complete the contributor's
> agreement as described on https://docs.mulesoft.com/#making-a-contribution
> to register as a contributor so that we can accept your pull request.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mulesoft/mulesoft-docs/pull/446#issuecomment-212011726>
>



-- 

*Thanks Rajesh Kumar*

**Comment by george-hoffer** [comment]
Merged. Thank you for helping to improve MuleSoft documentation. 
Regards.

**Pull request merged**
