### PR TITLE
add missing types keyvalues and rateLimits

### PR DESCRIPTION
**Pull request by n2ygk**
keyvalues was seen in a custom policy example. rateLimits is also shown as a choice in Studio when editing the YAML.

### CODE REVIEW

**Comment by george-hoffer** [comment]
Thank you for your contribution. Please complete the contributor's agreement as described at https://github.com/mulesoft/mulesoft-docs/blob/master/README.adoc to register as a contributor so that we can accept your pull request.

**Comment by krishahn** [comment]
Checking with Engineering about completeness of custom policy type list for the yaml.

**Comment by n2ygk** [comment]
I tried following the instructions but the API notebook opened empty (no
form to fill out).

**Comment by fermujica** [comment]
Thanks, @n2ygk! The missing Contributor's Agreement form seems like an issue on our end. 
I'm looking into it.

**Pull request merged**
