### PR TITLE
PCF now GA - remove beta ref

### PR DESCRIPTION
**Pull request by gajitt**
Removed the two instances where PCF deployment was mentioned as being in beta

### CODE REVIEW

**Comment by gajitt** [comment]
@sleslie23 I think this is your page :)

**Comment by gajitt** [comment]
Also- Just talked to Pablo Luna and Fede - Hybrid Insights is also mentioned as being in beta on this page and it is not - so those lines should also be removed.

**Comment by sleslie23** [comment]
Thanks @gajitt. I also have this change in a branch I'm about to merge. I'll fix the references to Hybrid Insights also.

FYI, we are trying to scattering reference to PCE throughout the docs. It's a maintenance nightmare.

Thanks again!

**Comment by george-hoffer** [comment]
Hi Gajitt, thank you for your contribution. Please complete the contributor's agreement as described at https://github.com/mulesoft/mulesoft-docs/blob/master/README.adoc to register as a contributor so that we can accept your pull request.

**Comment by gajitt** [comment]
Done - didn't know it applied to internal ppl too.

**Comment by george-hoffer** [comment]
We can't tell who someone is by their git name. Unfortunately your git profile doesn't list your real name and only shows one git checkin. Similarly searches on the outer web found only few gajitt references and none to someone who works here. If you list your real name, we're happy to process your contributions faster.

**Pull request merged**
