### PR TITLE
MERGE on Oct 7: Multi region replay data

### PR DESCRIPTION
**Pull request by nishantkakar**

### CODE REVIEW

**Comment by sleslie23** [comment]
@nishantkakar @fedebongio This PR says WIP. Is it ready to be merged?

**Comment by nishantkakar** [comment]
Not right now, we want to merge it next Saturday. Oct 7, 2017

**Comment by sleslie23** [comment]
@nishantkakar Ok, I updated the title so no one merges it by mistake. Thanks!

**Comment by nishantkakar** [comment]
Thank you @sleslie23 :)

**Comment by sleslie23** [comment]
Thanks @fedebongio

**Pull request merged**
