### PR TITLE
Update shading-libraries.adoc

### PR DESCRIPTION
**Pull request by tonedef71**
I found the original documentation for using the shade plugin to be confusing and unhelpful.  Hopefully, these proposed changes are an improvement.

### CODE REVIEW

**Comment by george-hoffer** [comment]
Hi Anthony, Please complete the contributor's agreement as described at https://github.com/mulesoft/mulesoft-docs/blob/master/README.adoc to register as a contributor so that we can accept your pull requests. Thank you!!

**Comment by tonedef71** [comment]
Hello George:

Why do I need to do it again?  I did so already last May:
https://github.com/mulesoft/contributor-agreements/issues/163

--Anthony

**Comment by george-hoffer** [comment]
Hi Anthony, All the rest of our contributor agreements are listed as open. #163 is closed and was missed by our checking software. Thanks for confirming.

**Comment by tonedef71** [comment]
Is "SharkBerto" still the reviewer for this request?

**Comment by george-hoffer** [comment]
Thank you Anthony!!

**Pull request merged**
