### PR TITLE
Properties details

### PR DESCRIPTION
**Pull request by ethanport**
Compare on-premises life-cycle with CloudHub
Describe secure properties scenarios, options and behavior

### CODE REVIEW

**Comment by ethanport** [comment]
This should be reviewed and edited, perhaps with some example images added showing the hidden values once the application is deployed.

**Comment by nearnshaw** [comment]
This is a really great addition, Ethan, thanks!
I'm currently going through a process of restructuring and refactoring all of our CloudHub content, and planning to release those docs a month from now. For now this exists in a separate GitHub branch that is still unpublished.  https://github.com/mulesoft/mulesoft-docs/tree/Runtime-Manager-rename-2016
I'm going to merge your request as it is, with some minor edits. But also I'm going to take the contet in it and paste it in different documents, where it fits in better with the new structure.
On a side note, does the command example work as it is? Don't you also need to include an -M argument? As in below:
mule -M-Dsecret.key=toSecretPassword -M-Denv=prod -M-Ddb.password=secretPassword -app myApp.zip

**Comment by ethanport** [comment]
Yes, you do need to include -M-D, not -D. I probably copied those from my
Mule Studio project debug session, where you do not include the -M. Also it
should be topSecretPassword, not toSecretPassword. Let me take a look again
and what I submitted :)

-Ethan

On Mon, Mar 7, 2016 at 1:33 PM, Nicolas Earnshaw <notifications@github.com>
wrote:

> Merged #348 <https://github.com/mulesoft/mulesoft-docs/pull/348>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mulesoft/mulesoft-docs/pull/348#event-580810601>.
>



-- 
<http://www.mulesoft.com/>
Ethan Port, Principal Courseware Developer | MuleSoft
<http://www.mulesoft.com>

77 Geary St, 2nd Floor, San Francisco, CA 94108

M +1 650.619.3695 <+1+650.619.3695>* Skype *ethan.port
@learnmulesoft <https://twitter.com/learnmulesoft>

<https://www.linkedin.com/company/www.mulesoft.com>
<https://twitter.com/mulesoft>   <https://www.facebook.com/MuleSoft>
<https://www.youtube.com/user/mulesoftvids> We're hiring!
<http://www.mulesoft.com/careers>

**Comment by ethanport** [comment]
The example command should be:

mule -M-Dsecret.key=topSecretPassword -M-Denv=prod -M-Ddb.host=prod-db.mycompany.com -app myApp.zip

**Pull request merged**
