### PR TITLE
[DO NOT MERGE] Update DNS in Cloudhub Networking Guide

### PR DESCRIPTION
**Pull request by nishantkakar**

### CODE REVIEW

**Comment by sleslie23** [comment]
@nishantkakar Please include me as a reviewer on any doc PRs. That will make the process go much faster.

**Comment by sleslie23** [comment]
Do not merge until the upcoming CH release.

**Comment by Mulesoft-Mysti** [comment]
@sleslie23 okay to merge?

**Comment by nishantkakar** [comment]
Yes, should be merged now.

**Pull request merged**
