### PR TITLE
Fix typo in dataweave-migrator.adoc

### PR DESCRIPTION
**Pull request by thatchej**

### CODE REVIEW

**Comment by nearnshaw** [comment]
Thank you for helping improve MuleSoft documentation. Please complete the http://www.mulesoft.org/legal/contributor-agreement.html[Contributor's Agreement] so we can give you credit for your submission.

**Comment by thatchej** [comment]
I agree to the Contributor's Agreement

**Comment by nearnshaw** [comment]
I'm sorry we have to make you do all of this for approving a simple typo correction, but I'm afraid that to accept the contributor's agreement properly you must do it through this link (sorry I wasn't clear about that in my previous comment)
https://api-notebook.anypoint.mulesoft.com/notebooks/#380297ed0e474010ff43
All you have to do in this page is click the Play button at the top, and then respond to any prompts that appear

**Comment by thatchej** [comment]
Hey no worries at all! I finished it up and hope my small one letter change
can now be accepted :)

On Tue, Jan 19, 2016 at 11:39 AM, Nicolas Earnshaw <notifications@github.com

**Comment by nearnshaw** [comment]
Wow I really appreciate your commitment, thank you so much!  I'll approve your contribution right away! :)

**Comment by seanosterberg** [comment]
@thatchej, thanks again for taking the time!

**Pull request merged**
